# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: "Magazine du Webdesign &ndash; Design inspiration & ressources Web"
description:
url: http://www.magazineduwebdesign.com
twitter_username: MagDuWebdesign
# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: .tmp/src
destination: .tmp/dist
exclude: ['assets']
include: ['.nojekyll']
# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: guillaumepalayer
  email: guillaume.palayer@gmail.com
  avatar: avatar-88.jpg
  twitter: guillaumpalayer
# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
permalink: /:title/
paginate: 10
paginate_path: 'page:num'
excerpt_separator: ''

# Markdown library and options
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: rouge

# Extending Jekyll
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Collections settings
collections:
  note:
    output: true
    permalink: /:collection/:title/
  collection:
    output: true
    permalink: /:collection/:title/
  offre-emploi:
    output: true
    permalink: /:collection/:title/
  conseil-candidater:
    output: true
    permalink: /:collection/:title/
  conseil-recruter:
    output: true
    permalink: /:collection/:title/

# Defaults front matter variables for various types
# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      auteur: "MagDuWebdesign" # overrides previous default layout
      bgimgheader: "false"
  -
    scope:
      path: "note"
      type: "note"
    values:
      layout: "note" # overrides previous default layout
  -
    scope:
      path: "collection"
      type: "collection"
    values:
      layout: "collection" # overrides previous default layout
      bgimgheader: "false"
  -
    scope:
      path: "offre-emploi"
      type: "offre-emploi"
    values:
      layout: "emploi" # overrides previous default layout
      bgimgheader: "false"
  -
    scope:
      path: "conseil-candidater"
      type: "conseil-candidater"
    values:
      layout: "candidater" # overrides previous default layout
      bgimgheader: "false"
  -
    scope:
      path: "conseil-recruter"
      type: "conseil-recruter"
    values:
      layout: "recruter" # overrides previous default layout
      bgimgheader: "false"

  # videos - overrides default permlink
  -
    scope:
      path: "videos"
      type: "posts"
    values:
      permalink: "/videos/:title/"

  # ressources - overrides default permlink
  -
    scope:
      path: "ressources/ressources-icones"
      type: "posts"
    values:
      permalink: "/ressources/icones/:title/"
  -
    scope:
      path: "ressources/ressources-kits-ui"
      type: "posts"
    values:
      permalink: "/ressources/kits-ui/:title/"
  -
    scope:
      path: "ressources/ressources-mockups"
      type: "posts"
    values:
      permalink: "/ressources/mockups/:title/"
  -
    scope:
      path: "ressources/ressources-outils-services"
      type: "posts"
    values:
      permalink: "/ressources/outils-services/:title/"
  -
    scope:
      path: "ressources/ressources-outils-services/ressources-outils-services-design"
      type: "posts"
    values:
      permalink: "/ressources/outils-services/design/:title/"
  -
    scope:
      path: "ressources/ressources-themes-jekyll"
      type: "posts"
    values:
      permalink: "/ressources/themes-jekyll/:title/"
  -
    scope:
      path: "ressources/ressources-themes-joomla"
      type: "posts"
    values:
      permalink: "/ressources/themes-joomla/:title/"
  -
    scope:
      path: "ressources/ressources-themes-wordpress"
      type: "posts"
    values:
      permalink: "/ressources/themes-wordpress/:title/"

  # inspirations - overrides default permlink
  -
    scope:
      path: "inspirations/inspirations-code-art"
      type: "posts"
    values:
      permalink: "/inspirations/code-art/:title/"
  -
    scope:
      path: "inspirations/inspirations-parcours-apps-ios"
      type: "posts"
    values:
      permalink: "/inspirations/parcours-apps-ios/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-android-wear"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/android-wear/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-apple-watch"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/apple-watch/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-connected-car"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/connected-car/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-sites-web"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/sites-web/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-animations"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/animations/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-tv"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/tv/:title/"

  # evenements - overrides default permlink
  -
    scope:
      path: "evenements/developpement-web"
      type: "posts"
    values:
      permalink: "/evenements/developpement-web-devops/:title/"
  -
    scope:
      path: "evenements/evenements-design"
      type: "posts"
    values:
      permalink: "/evenements/web-design/:title/"
  -
    scope:
      path: "evenements/evenements-ux-design"
      type: "posts"
    values:
      permalink: "/evenements/ux-design/:title/"

  # deals - overrides default permlink
  -
    scope:
      path: "deals"
      type: "posts"
    values:
      permalink: "/deals/:title/"

  # conseils - overrides default permlink
  -
    scope:
      path: "conseils/conseils-guide"
      type: "posts"
    values:
      permalink: "/conseils/guides/:title/"
  -
    scope:
      path: "conseils/conseils-livres"
      type: "posts"
    values:
      permalink: "/conseils/livres/:title/"
  -
    scope:
      path: "conseils/conseils-podcasts"
      type: "posts"
    values:
      permalink: "/conseils/podcasts/:title/"

# Jekyll Data Pages Generator : this generator allows one to specify data files for which we want to generate one page per record.
page_gen:
  - data: "inspirations-ui-sites-web"
    template: "inspirations-sites-web-no-tags"
    name: "title"
    dir: "/inspirations/ui-design/sites-web/"

  - data: "inspirations-ui-animations"
    template: "inspirations-animations"
    name: "title"
    dir: "/inspirations/ui-design/animations/"