# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

# Site settings différent for build (.dist)
url: "http://www.magazineduwebdesign.com"

future: false
show_drafts: false
