# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

# Site settings
title: "Magazine du Webdesign &ndash; Inspiration & ressources Web"
description:
author:
  name: guillaumepalayer
  email: guillaume.palayer@gmail.com
  avatar: avatar-88.jpg

twitter_username: MagDuWebdesign
github_username: jekyll
source: app
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title
url: "http://localhost:9000" # the base hostname & protocol for your site
highlighter: rouge
# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.nojekyll']
# Collections settings
collections:
  encyclo:
    output: true
    permalink: /:collection/:title/
  note:
    output: true
    permalink: /:collection/:title/
  collection:
    output: true
    permalink: /:collection/:title/
  offre-emploi:
    output: true
    permalink: /:collection/:title/
  conseil-candidater:
    output: true
    permalink: /:collection/:title/
  conseil-recruter:
    output: true
    permalink: /:collection/:title/

# Defaults front matter variables for various types
# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      auteur: "MagDuWebdesign" # overrides previous default layout
      bgimgheader: "false"
  -
    scope:
      path: "note"
      type: "note"
    values:
      layout: "note" # overrides previous default layout
  -
    scope:
      path: "apprendre/encyclo"
      type: "encyclo"
    values:
      layout: "encyclo" # overrides previous default layout
      bgimgheader: "false"
  -
    scope:
      path: "collection"
      type: "collection"
    values:
      layout: "collection" # overrides previous default layout
      bgimgheader: "false"
  -
    scope:
      path: "offre-emploi"
      type: "offre-emploi"
    values:
      layout: "emploi" # overrides previous default layout
      bgimgheader: "false"
  -
    scope:
      path: "conseil-candidater"
      type: "conseil-candidater"
    values:
      layout: "candidater" # overrides previous default layout
      bgimgheader: "false"
  -
    scope:
      path: "conseil-recruter"
      type: "conseil-recruter"
    values:
      layout: "recruter" # overrides previous default layout
      bgimgheader: "false"

  # videos - overrides default permlink
  -
    scope:
      path: "videos"
      type: "posts"
    values:
      permalink: "/videos/:title/"

  # ressources - overrides default permlink
  -
    scope:
      path: "ressources/ressources-accessoires-fournitures"
      type: "posts"
    values:
      permalink: "/ressources/accessoires-fournitures/:title/"
  -
    scope:
      path: "ressources/ressources-fonts"
      type: "posts"
    values:
      permalink: "/ressources/fonts/:title/"
  -
    scope:
      path: "ressources/ressources-icones"
      type: "posts"
    values:
      permalink: "/ressources/icones/:title/"
  -
    scope:
      path: "ressources/ressources-kits-ui"
      type: "posts"
    values:
      permalink: "/ressources/kits-ui/:title/"
  -
    scope:
      path: "ressources/ressources-mockups"
      type: "posts"
    values:
      permalink: "/ressources/mockups/:title/"
  -
    scope:
      path: "ressources/ressources-outils-services"
      type: "posts"
    values:
      permalink: "/ressources/outils-services/:title/"
  -
    scope:
      path: "ressources/ressources-outils-services/ressources-outils-services-design"
      type: "posts"
    values:
      permalink: "/ressources/outils-services/design/:title/"
  -
    scope:
      path: "ressources/ressources-sketch"
      type: "posts"
    values:
      permalink: "/ressources/application-sketch/:title/"
  -
    scope:
      path: "ressources/ressources-themes-drupal"
      type: "posts"
    values:
      permalink: "/ressources/themes-drupal/:title/"
  -
    scope:
      path: "ressources/ressources-themes-ghost"
      type: "posts"
    values:
      permalink: "/ressources/themes-ghost/:title/"
  -
    scope:
      path: "ressources/ressources-themes-jekyll"
      type: "posts"
    values:
      permalink: "/ressources/themes-jekyll/:title/"
  -
    scope:
      path: "ressources/ressources-themes-joomla"
      type: "posts"
    values:
      permalink: "/ressources/themes-joomla/:title/"
  -
    scope:
      path: "ressources/ressources-themes-shopify"
      type: "posts"
    values:
      permalink: "/ressources/themes-shopify/:title/"
  -
    scope:
      path: "ressources/ressources-themes-tumblr"
      type: "posts"
    values:
      permalink: "/ressources/themes-tumblr/:title/"
  -
    scope:
      path: "ressources/ressources-themes-wordpress"
      type: "posts"
    values:
      permalink: "/ressources/themes-wordpress/:title/"

  # inspirations - overrides default permlink
  -
    scope:
      path: "inspirations/inspirations-code-art"
      type: "posts"
    values:
      permalink: "/inspirations/code-art/:title/"
  -
    scope:
      path: "inspirations/inspirations-parcours-apps-android"
      type: "posts"
    values:
      permalink: "/inspirations/parcours-apps-android/:title/"
  -
    scope:
      path: "inspirations/inspirations-parcours-apps-ios"
      type: "posts"
    values:
      permalink: "/inspirations/parcours-apps-ios/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-android-wear"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/android-wear/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-apple-watch"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/apple-watch/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-connected-car"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/connected-car/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-material-design"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/material-design/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-sites-web"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/sites-web/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-animations"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/animations/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-tv"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/tv/:title/"
  -
    scope:
      path: "inspirations/inspirations-ui-web-vr"
      type: "posts"
    values:
      permalink: "/inspirations/ui-design/web-vr/:title/"

  # evenements - overrides default permlink
  -
    scope:
      path: "evenements/developpement-web"
      type: "posts"
    values:
      permalink: "/evenements/developpement-web-devops/:title/"
  -
    scope:
      path: "evenements/evenements-design"
      type: "posts"
    values:
      permalink: "/evenements/web-design/:title/"
  -
    scope:
      path: "evenements/evenements-ux-design"
      type: "posts"
    values:
      permalink: "/evenements/ux-design/:title/"

  # conseils - overrides default permlink
  -
    scope:
      path: "conseils/conseils-citations"
      type: "posts"
    values:
      permalink: "/conseils/citations/:title/"
  -
    scope:
      path: "conseils/conseils-guide"
      type: "posts"
    values:
      permalink: "/conseils/guides/:title/"
  -
    scope:
      path: "conseils/conseils-livres"
      type: "posts"
    values:
      permalink: "/conseils/livres/:title/"
  -
    scope:
      path: "conseils/conseils-podcasts"
      type: "posts"
    values:
      permalink: "/conseils/podcasts/:title/"

# Jekyll Data Pages Generator : this generator allows one to specify data files for which we want to generate one page per record.
page_gen:
  - data: "inspirations-ui-sites-web"
    template: "inspirations-sites-web-no-tags"
    name: "title"
    dir: "/inspirations/ui-design/sites-web/"

  - data: "inspirations-ui-animations"
    template: "inspirations-animations"
    name: "title"
    dir: "/inspirations/ui-design/animations/"

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Conversion
markdown: kramdown

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
